- id: fb01f50f6e484d7fb623365e9a0b5f52
  alias: Reset waste notification
  trigger:
    platform: state
    entity_id: input_boolean.waste_moved
    to: 'on'
    for:
      hours: 12
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.waste_moved
  - service: input_boolean.turn_on
    entity_id: input_boolean.waste_reminder
- id: f276d37dd7b4490d9e5212c91fdeeba0
  alias: Mark waste as moved from notification
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: MARK_WASTE_MOVED
    id: waste_moved_by_bauke
    context:
      user_id:
      - f976a4bc7f22438e93c9a9cd0b47c627
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: MARK_WASTE_MOVED
    id: waste_moved_by_anouk
    context:
      user_id:
      - 630c9bfb3f084bf1b7133da9a16ff5ec
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: MARK_WASTE_MOVED
    context: {}
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.waste_moved
  - choose:
    - conditions:
      - condition: trigger
        id: waste_moved_by_bauke
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.who_moved_trash
        data:
          option: Bauke
    - conditions:
      - condition: trigger
        id: waste_moved_by_anouk
      sequence:
      - service: input_select.select_option
        target:
          entity_id: input_select.who_moved_trash
        data:
          option: Anouk
    default:
    - service: input_select.select_option
      target:
        entity_id: input_select.who_moved_trash
      data:
        option: default
  - service: notify.notify
    data:
      title: '{{ states.input_select.who_moved_trash.state }} heeft de {% if is_state(''sensor.afvalwijzer_tomorrow'',
        ''Geen'') %}vuilnis{% else %}{{states.sensor.afvalwijzer_tomorrow.state}}{%
        endif %} container buiten gezet'
      message: Chill, dan hoef jij het niet meer te doen!
  - service: input_select.select_option
    target:
      entity_id: input_select.who_moved_trash
    data:
      option: default
- id: b95aa77fdde0437e9f7a65d0d7bfe860
  alias: Waste has not been moved
  trigger:
  - platform: time_pattern
    hours: /1
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.waste_moved
      state: 'off'
    - condition: state
      entity_id: input_boolean.waste_reminder
      state: 'on'
    - condition: time
      after: '18:00:00'
      before: '23:00:00'
    - condition: template
      value_template: '{{ states(''sensor.afvalwijzer_tomorrow'') != ''Geen'' }}'
  action:
  - service: notify.notify
    data:
      title: Morgen wordt het {% if is_state('sensor.afvalwijzer_tomorrow', 'Geen')
        %}vuilnis{% else %}{{states.sensor.afvalwijzer_tomorrow.state}}{% endif %}
        opgehaald
      message: Denk je er aan om de {% if is_state('sensor.afvalwijzer_tomorrow',
        'Geen') %}vuilnis{% else %}{{states.sensor.afvalwijzer_tomorrow.state}}{%
        endif %} container buiten te zetten?
      data:
        actions:
        - action: MARK_WASTE_MOVED
          title: Voltooien
          icon: sfsymbols:checkmark.circle
        - action: DISMISS
          title: Herinner mij later
          icon: sfsymbols:timer
- id: 5915b26e208d473792ef74e0e693172c
  alias: Turn off heating when room's window is left open
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.werkkamer_bauke_open_window
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  action:
  - service: notify.mobile_app_iphone_van_bauke
    data:
      title: Test
      message: Window has been left open
- id: '1636147330331'
  alias: Schakel Tado uit als er niemand thuis is
  description: ''
  trigger:
  - platform: zone
    entity_id: person.anouk
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: person.bauke
    zone: zone.home
    event: leave
  - platform: template
    value_template: '{{ not is_state(''person.bauke'', ''home'') and not is_state(''person.anouk'',
      ''home'') }}'
  condition:
  - condition: state
    entity_id: input_boolean.heating_geolocation
    state: 'on'
  action:
  - service: notify.family
    data:
      title: Verwarming uitgeschakeld
      message: Je Tado is op 'afwezig' gezet omdat er niemand thuis is.
  - service: climate.set_preset_mode
    data:
      preset_mode: away
    target:
      area_id: woonkamer
  mode: single
- id: '1636147330332'
  alias: Schakel Tado in als er iemand thuis komt
  description: ''
  trigger:
  - platform: zone
    entity_id: person.anouk
    zone: zone.home
    event: enter
    id: sjdsab7yiu3h42j
  - platform: zone
    entity_id: person.bauke
    zone: zone.home
    event: enter
    id: dasd5u76ias8ud
  - platform: template
    value_template: '{{ is_state(''person.bauke'', ''home'') or is_state(''person.anouk'',
      ''home'') }}'
  condition:
  - condition: state
    entity_id: input_boolean.heating_geolocation
    state: 'on'
  action:
  - service: notify.family
    data:
      title: Verwarming ingeschakeld
      message: Welkom thuis! Je Tado is ingeschakeld.
  - service: climate.set_preset_mode
    data:
      preset_mode: none
    target:
      area_id: woonkamer
  mode: single
- id: '1653435434932'
  alias: Sound the alarm iOS
  description: Motion based alarm
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: SOUND_ALARM
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      title: Alarm gaat af
      message: test
  - service: notify.family
    data:
      title: Alarm gaat af
      message: Test
  mode: single
- id: '1653684999337'
  alias: Toggle Movie Mode with Ikea button
  description: Toggle movie mode input_boolean when remote is clicked
  trigger:
  - platform: device
    domain: mqtt
    device_id: 508c16ba1e53972f58ff68751b6c12fa
    type: action
    subtype: 'on'
    discovery_id: 0x680ae2fffe80376e action_on
  - platform: device
    domain: mqtt
    device_id: 508c16ba1e53972f58ff68751b6c12fa
    type: action
    subtype: 'off'
    discovery_id: 0x680ae2fffe80376e action_off
  condition: []
  action:
  - service: homeassistant.toggle
    entity_id: input_boolean.movie_mode
  mode: single
- id: '1653685711883'
  alias: Turn on Movie Mode
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.movie_mode
    to: 'on'
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - keuken
      - entree
    data:
      transition: 10
  - service: hue.hue_activate_scene
    data:
      scene_name: Film kijken
      group_name: Woonkamer
      dynamic: true
      transition: 10
  - service: switch.turn_off
    target:
      entity_id:
      - switch.hue_motion_sensor_1_motion
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
    data: {}
  mode: single
- id: '1653686032957'
  alias: Turn off Movie Mode
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.movie_mode
    to: 'off'
  condition: []
  action:
  - service: hue.hue_activate_scene
    data:
      scene_name: Helder
      group_name: Woonkamer
      dynamic: true
      transition: 10
  - service: switch.turn_on
    target:
      entity_id:
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
      - switch.hue_motion_sensor_1_motion
  mode: single
- id: '1654533597100'
  alias: Slaapkamer auto lights off
  description: Turn lights off after 30 minutes
  trigger:
  - device_id: 1c6a455d3533567404ec57126e82a5c8
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: c8c805fc-a934-4da1-903e-7756a7ef261b
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: a74e5afe63f2bb54544c6cb68f271511
    entity_id: light.hue_ambiance_spot_1
    domain: light
  - type: turn_off
    device_id: ae08ad1e58ab9a2e3092538b629abd07
    entity_id: light.hue_ambiance_spot_2
    domain: light
  - type: turn_off
    device_id: 290589317f10ecd65fe9cb6ea6f4a903
    entity_id: light.hue_ambiance_spot_3
    domain: light
  mode: single
- id: '1658504908669'
  alias: Turn off motions sensor when Sleeping Mode is on
  description: Turn off motion sensors on ground floor when Sleeping mode is on
  trigger:
  - platform: state
    entity_id: input_boolean.sleeping_mode
    to: 'on'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.hue_motion_sensor_1_motion
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
      - switch.hue_motion_sensor_1_motion_2
    data: {}
  mode: single
- id: '1658505514384'
  alias: Turn on motions sensor when Sleeping Mode is off
  description: Turn on motion sensors on ground floor when Sleeping mode is off
  trigger:
  - platform: state
    entity_id: input_boolean.sleeping_mode
    to: 'off'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.hue_motion_sensor_1_motion
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
  mode: single
- id: '1663687898960'
  alias: Livingroom Music Schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.livingroom_music_schedule
  condition: []
  action:
  - if:
    - condition: state
      entity_id: schedule.livingroom_music
      state: 'on'
    then:
    - service: media_player.media_play
      data: {}
      target:
        entity_id: media_player.living_room
    else:
    - service: media_player.media_stop
      data: {}
      target:
        entity_id: media_player.living_room
  mode: single
- id: '1664198952463'
  alias: Vloerverwarmingspomp
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.woonkamer_heating
  condition: []
  action:
  - if:
    - condition: numeric_state
      entity_id: sensor.woonkamer_heating
      above: 1
    then:
    - type: turn_on
      device_id: d5a3700f94c3754f3d601c79ffdcaabd
      entity_id: switch.vloerverwarmingspomp
      domain: switch
    else:
    - type: turn_off
      device_id: d5a3700f94c3754f3d601c79ffdcaabd
      entity_id: switch.vloerverwarmingspomp
      domain: switch
  mode: restart
- id: '1664400231614'
  alias: Turn on Slaapkamer Motion sensor in the morning
  description: Turn on motion sensor Slaapkamer
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.hue_motion_sensor_1_motion_2
  mode: single
- id: '1664453910816'
  alias: Turn on Espresso Machine when enough PV overproduction
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: ca489ceb3372a21d9b413f76f07d26c2
    entity_id: sensor.energy_active_power
    domain: sensor
    below: -1400
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: time
    after: 09:00:00
    before: '12:00:00'
    enabled: true
  - condition: device
    type: is_off
    device_id: 29d22d3df71910ad86405bb7d5154123
    entity_id: light.espressomachine
    domain: light
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.bauke
      zone: zone.home
    - condition: zone
      entity_id: person.anouk
      zone: zone.home
  action:
  - service: notify.notify
    data:
      message: Er is genoeg overproductie ☀️
      title: Espresso Machine ingeschakeld
  - type: turn_on
    device_id: 29d22d3df71910ad86405bb7d5154123
    entity_id: light.espressomachine
    domain: light
  mode: single
- id: '1664454667785'
  alias: Notify when there is a lot of overproduction
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: ca489ceb3372a21d9b413f76f07d26c2
    entity_id: sensor.energy_active_power
    domain: sensor
    below: -1500
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
  - condition: template
    value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.notify_overproduction",
      "last_triggered") | default(0)) | int > 28800 )}}'
  action:
  - service: notify.notify
    data:
      title: Let the sun shine! ⚡️
      message: Je produceert nu veel stroom, tijd om een wasje te draaien?
  mode: single
- id: '1664540486301'
  alias: Turn on Schuurverwarming when enough PV overproduction
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: ca489ceb3372a21d9b413f76f07d26c2
    entity_id: sensor.energy_active_power
    domain: sensor
    below: -750
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: device
    type: is_off
    device_id: 524e63a9251c50afcac3f73c6e8866bb
    entity_id: light.elektrische_verwarming
    domain: light
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.bauke
      zone: zone.home
    - condition: zone
      entity_id: person.anouk
      zone: zone.home
  - condition: not
    conditions:
    - condition: time
      after: 09:00:00
      before: '13:00:00'
  action:
  - service: notify.mobile_app_iphone
    data:
      title: Schuurverwarming ingeschakeld
      message: Er is genoeg overproductie ☀️
  - type: turn_on
    device_id: 524e63a9251c50afcac3f73c6e8866bb
    entity_id: light.elektrische_verwarming
    domain: light
  mode: single
- id: '1664540770914'
  alias: Turn off Schuurverwarming when not enough PV overproduction or at sunset
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: ca489ceb3372a21d9b413f76f07d26c2
    entity_id: sensor.energy_active_power
    domain: sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
    above: 0
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: state
    entity_id: light.elektrische_verwarming
    state: 'on'
  action:
  - service: notify.mobile_app_iphone
    data:
      title: Schuurverwarming uitgeschakeld
      message: Te weinig overproductie
  - type: turn_off
    device_id: 524e63a9251c50afcac3f73c6e8866bb
    entity_id: light.elektrische_verwarming
    domain: light
  mode: single
- id: '1664802828599'
  alias: Turn on Espresso Machine at 12:00 when not enough PV production
  description: ''
  trigger:
  - platform: time
    at: '11:59:55'
  condition:
  - condition: device
    type: is_off
    device_id: 29d22d3df71910ad86405bb7d5154123
    entity_id: light.espressomachine
    domain: light
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.bauke
      zone: zone.home
    - condition: zone
      entity_id: person.anouk
      zone: zone.home
  action:
  - service: notify.notify
    data:
      message: "Er is te weinig zonne energie \U0001F976"
      title: Espresso Machine ingeschakeld
  - type: turn_on
    device_id: 29d22d3df71910ad86405bb7d5154123
    entity_id: light.espressomachine
    domain: light
  mode: single
- id: '1664815772089'
  alias: Sleep schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.sleep_schedule
  condition: []
  action:
  - if:
    - condition: state
      entity_id: schedule.sleep_schedule
      state: 'on'
    then:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.sleeping_mode
    else:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.sleeping_mode
  mode: single
- id: '16884829476049'
  alias: "Turn On Living Room TV with WakeOnLan"
  trigger:
    - platform: webostv.turn_on
      entity_id: media_player.lg_tv
  action:
    - service: wake_on_lan.send_magic_packet
      data:
        mac: 74:40:BE:B6:8B:E8
