- id: 5915b26e208d473792ef74e0e693172c
  alias: WINDOW_LEFT_OPEN
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.werkkamer_bauke_open_window
    - binary_sensor.badkamer_open_window
    - binary_sensor.logeerkamer_open_window
    - binary_sensor.slaapkamer_open_window
    - binary_sensor.werkkamer_anouk_open_window
    - binary_sensor.woonkamer_open_window
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  condition:
  - condition: state
    entity_id: input_boolean.heating_open_window_detection
    state: 'on'
  action:
  - service: notify.notify
    data:
      title: Verwarming
      message: Open raam gedetecteerd in {{ 'de'+ area_name('trigger.entity_id') if
        trigger.entity_id is defined else 'onbekende ruimte'}}
- id: '1653435434932'
  alias: Sound the alarm iOS
  description: Motion based alarm
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: SOUND_ALARM
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      title: Alarm gaat af
      message: test
  - service: notify.notify
    data:
      title: Alarm gaat af
      message: Test
  mode: single
- id: '1653685711883'
  alias: Turn on Movie Mode
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.movie_mode
    to: 'on'
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - keuken
      - entree
    data:
      transition: 10
  - service: hue.hue_activate_scene
    data:
      scene_name: Film kijken
      group_name: Woonkamer
      dynamic: true
      transition: 10
  - service: switch.turn_off
    target:
      entity_id:
      - switch.hue_motion_sensor_1_motion
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
    data: {}
  mode: single
- id: '1653686032957'
  alias: Turn off Movie Mode
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.movie_mode
    to: 'off'
  condition: []
  action:
  - service: hue.hue_activate_scene
    data:
      scene_name: Helder
      group_name: Woonkamer
      dynamic: true
      transition: 10
  - service: switch.turn_on
    target:
      entity_id:
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
      - switch.hue_motion_sensor_1_motion
  mode: single
- id: '1654533597100'
  alias: Slaapkamer auto lights off
  description: Turn lights off after 30 minutes
  trigger:
  - device_id: 1c6a455d3533567404ec57126e82a5c8
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: c8c805fc-a934-4da1-903e-7756a7ef261b
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: a74e5afe63f2bb54544c6cb68f271511
    entity_id: light.hue_ambiance_spot_1
    domain: light
  - type: turn_off
    device_id: ae08ad1e58ab9a2e3092538b629abd07
    entity_id: light.hue_ambiance_spot_2
    domain: light
  - type: turn_off
    device_id: 290589317f10ecd65fe9cb6ea6f4a903
    entity_id: light.hue_ambiance_spot_3
    domain: light
  mode: single
- id: '1658504908669'
  alias: sleep_mode_on
  description: Turn off motion sensors on ground floor when Sleeping mode is on
  trigger:
  - platform: state
    entity_id: input_boolean.sleep_mode
    to: 'on'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
      - switch.hue_motion_sensor_1_motion_2
    data: {}
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.all_group
      - light.espressomachine
  mode: single
- id: '1658505514384'
  alias: sleep_mode_off
  description: Turn on motion sensors on ground floor when Sleeping mode is off
  trigger:
  - platform: state
    entity_id: input_boolean.sleep_mode
    to: 'off'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
  mode: single
- id: '1663687898960'
  alias: Livingroom Music Schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.livingroom_music_schedule
  condition: []
  action:
  - if:
    - condition: state
      state: 'on'
      entity_id: schedule.livingroom_music_schedule
    then:
    - service: media_player.volume_set
      data:
        volume_level: 0.1
      target:
        entity_id: media_player.woonkamer
    - service: media_player.media_play
      data: {}
      target:
        entity_id: media_player.woonkamer
    else:
    - service: media_player.media_stop
      data: {}
      target:
        entity_id: media_player.woonkamer
  mode: single
- id: '1664400231614'
  alias: Turn on Slaapkamer Motion sensor in the morning
  description: Turn on motion sensor Slaapkamer
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.hue_motion_sensor_1_motion_2
  mode: single
- id: '1664454667785'
  alias: Notify when there is a lot of overproduction
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: ca489ceb3372a21d9b413f76f07d26c2
    entity_id: sensor.p1_meter_active_power
    domain: sensor
    below: -1500
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
  - condition: template
    value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.notify_overproduction",
      "last_triggered") | default(0)) | int > 28800 )}}'
  action:
  - service: notify.notify
    data:
      title: Let the sun shine! ⚡️
      message: Je produceert nu veel stroom, tijd om een wasje te draaien?
  mode: single
- id: '1664540486301'
  alias: Turn on Schuurverwarming when enough PV overproduction
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: ca489ceb3372a21d9b413f76f07d26c2
    entity_id: sensor.p1_meter_active_power
    domain: sensor
    below: -750
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: device
    type: is_off
    device_id: 524e63a9251c50afcac3f73c6e8866bb
    entity_id: light.elektrische_verwarming
    domain: light
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.bauke
      zone: zone.home
    - condition: zone
      entity_id: person.anouk
      zone: zone.home
  - condition: not
    conditions:
    - condition: time
      after: 09:00:00
      before: '13:00:00'
  action:
  - service: notify.mobile_app_iphone_van_bauke
    data:
      title: Schuurverwarming ingeschakeld
      message: Genoeg overproductie ☀️
  - type: turn_on
    device_id: 524e63a9251c50afcac3f73c6e8866bb
    entity_id: light.elektrische_verwarming
    domain: light
  mode: single
- id: '1664540770914'
  alias: Turn off Schuurverwarming when not enough PV overproduction or at sunset
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: ca489ceb3372a21d9b413f76f07d26c2
    entity_id: sensor.p1_meter_active_power
    domain: sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
    above: 0
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: state
    entity_id: light.elektrische_verwarming
    state: 'on'
  action:
  - service: notify.mobile_app_iphone_van_bauke
    data:
      title: Schuurverwarming uitgeschakeld
      message: Te weinig overproductie
  - type: turn_off
    device_id: 524e63a9251c50afcac3f73c6e8866bb
    entity_id: light.elektrische_verwarming
    domain: light
  mode: single
- id: '1664815772089'
  alias: sleep_mode_schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.sleep_schedule
  condition: []
  action:
  - if:
    - condition: state
      entity_id: schedule.sleep_schedule
      state: 'on'
    then:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.sleep_mode
    else:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.sleep_mode
  mode: single
- id: '1666642536617'
  alias: security_garden_motion_detected
  description: Send a notification when motion is detected in the garden during the
    night
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.hue_outdoor_motion_sensor_1_motion
    to: 'on'
  condition:
  - condition: time
    after: '22:00:00'
    before: 08:00:00
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'on'
  action:
  - service: notify.notify
    data:
      message: Beweging gedetecteerd in de tuin, zijn de katten nog buiten?
      title: Beveiliging
  mode: single
- id: '1667243249878'
  alias: sleep_mode_turn_off_mobile_activity
  description: Turn off Sleep Mode based on iPhone's activity
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.iphone_van_anouk_focus
    - binary_sensor.iphone_van_bauke_focus
    from: 'on'
    to: 'off'
  condition:
  - condition: time
    after: 07:30:00
    before: '10:30:00'
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.sleep_mode
  mode: single
- id: '1667244491244'
  alias: tv_livingroom_pause_music
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.lg_tv
    to: 'on'
  condition:
  - condition: state
    entity_id: media_player.woonkamer
    state: playing
  action:
  - service: media_player.media_pause
    data: {}
    target:
      entity_id: media_player.woonkamer
  mode: single
- id: '1667575666527'
  alias: Movie Mode Toggle on/off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.movie_mode
  condition: []
  action:
  - if:
    - condition: state
      entity_id: input_boolean.movie_mode
      state: 'on'
    then:
    - service: light.turn_off
      target:
        area_id:
        - keuken
        - entree
        - hal
      data:
        transition: 10
    - service: hue.hue_activate_scene
      data:
        scene_name: Film kijken
        group_name: Woonkamer
        dynamic: true
        transition: 10
    - service: switch.turn_off
      target:
        entity_id:
        - switch.hue_motion_sensor_1_motion
        - switch.woonkamer_sensor_motion
        - switch.keuken_sensor_motion
      data: {}
    else:
    - service: hue.hue_activate_scene
      data:
        scene_name: Helder
        group_name: Woonkamer
        dynamic: true
        transition: 20
    - service: switch.turn_on
      target:
        entity_id:
        - switch.woonkamer_sensor_motion
        - switch.keuken_sensor_motion
        - switch.hue_motion_sensor_1_motion
      data: {}
  mode: single
- id: '1673136521824'
  alias: SLEEP_MODE_AUTOMATIC (TESTING)
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.hue_motion_sensor_1_motion_2
  condition:
  - condition: time
    after: '23:00:00'
    before: 06:00:00
  - condition: and
    conditions:
    - condition: template
      value_template: ''
  action: []
  mode: single
- id: '1673453436968'
  alias: SMOKE_ALARM_ERROR
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.rookmelder_entree_alarm
    attribute: linkquality
    to: '0'
  - platform: state
    entity_id:
    - switch.rookmelder_hal_alarm
    attribute: linkquality
    to: '0'
  - platform: state
    entity_id:
    - switch.rookmelder_overloop_alarm
    attribute: linkquality
    to: '0'
  condition: []
  action:
  - service: notify.mobile_app_iphone_van_bauke
    data:
      title: Rookmelder
      message: De rookmelder in de {{ area_name(trigger.entity_id) }} is buiten bereik
  mode: single
- id: '1673457099530'
  alias: SMOKE_ALARM_SMOKE_DETECTED
  description: ''
  trigger:
  - type: smoke
    platform: device
    device_id: fc94441be8c9f808c45345de27c04cb0
    entity_id: binary_sensor.rookmelder_entree_smoke
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: df06efb5000324afcb128bc292de1a7d
    entity_id: binary_sensor.rookmelder_hal_smoke
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: 4ba779a040c1088303a4f41e867c712f
    entity_id: binary_sensor.rookmelder_overloop_smoke
    domain: binary_sensor
  - type: smoke
    platform: device
    device_id: cfdcfd75618ab2d682697993c4457f12
    entity_id: binary_sensor.rookmelder_cv_kast
    domain: binary_sensor
  condition: []
  action:
  - service: notify.notify
    data:
      title: Rookmelder
      message: Er is rook gedetecteerd in de {{ area_name(trigger.entity_id) }}
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
  mode: single
- id: '1673737497198'
  alias: Sleep mode on by charging state
  description: Turn on Sleep Mode based on iPhone's charging state
  trigger:
  - platform: state
    entity_id:
    - sensor.iphone_van_bauke_battery_state
    - sensor.iphone_van_anouk_battery_state
    to: Charging
  condition:
  - condition: time
    after: '22:00:00'
    before: 05:00:00
  - condition: state
    entity_id: input_boolean.sleep_mode
    state: 'off'
  - condition: or
    conditions:
    - condition: and
      conditions:
      - condition: zone
        entity_id: person.bauke
        zone: zone.home
      - condition: state
        entity_id: sensor.iphone_van_bauke_battery_state
        state: Charging
      - condition: zone
        entity_id: person.anouk
        zone: zone.home
      - condition: state
        entity_id: sensor.iphone_van_anouk_battery_state
        state: Charging
    - condition: or
      conditions:
      - condition: and
        conditions:
        - condition: zone
          entity_id: person.bauke
          zone: zone.home
        - condition: not
          conditions:
          - condition: zone
            entity_id: person.anouk
            zone: zone.home
        - condition: state
          entity_id: sensor.iphone_van_bauke_battery_state
          state: Charging
      - condition: and
        conditions:
        - condition: zone
          entity_id: person.anouk
          zone: zone.home
        - condition: not
          conditions:
          - condition: zone
            entity_id: person.bauke
            zone: zone.home
        - condition: state
          entity_id: sensor.iphone_van_anouk_battery_state
          state: Charging
  action:
  - service: input_boolean.turn_on
    data: {}
    target:
      entity_id: input_boolean.sleep_mode
  mode: single
- id: '1675094284563'
  alias: SMOKE_ALARM_BATTERY_LOW
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.rookmelder_entree_alarm
    attribute: battery_low
    to: 'true'
  - platform: state
    entity_id:
    - switch.rookmelder_hal_alarm
    attribute: battery_low
    to: 'true'
  - platform: state
    entity_id:
    - switch.rookmelder_overloop_alarm
    attribute: battery_low
    to: 'true'
  - platform: state
    entity_id:
    - sensor.rookmelder_cv_kast_battery_state
    to: low
  condition: []
  action:
  - service: notify.notify
    data:
      title: Rookmelder
      message: De batterij van de rookmelder in de {{ area_name(trigger.entity_id)
        }} is bijna leeg
  mode: single
