- id: 5915b26e208d473792ef74e0e693172c
  alias: Turn off heating when room's window is left open
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.werkkamer_bauke_open_window
    to: 'on'
    for:
      hours: 0
      minutes: 0
      seconds: 0
  action:
  - service: notify.mobile_app_iphone_van_bauke
    data:
      title: Test
      message: Window has been left open
- id: '1636147330331'
  alias: Schakel Tado uit als er niemand thuis is
  description: ''
  trigger:
  - platform: zone
    entity_id: person.anouk
    zone: zone.home
    event: leave
  - platform: zone
    entity_id: person.bauke
    zone: zone.home
    event: leave
  - platform: template
    value_template: '{{ not is_state(''person.bauke'', ''home'') and not is_state(''person.anouk'',
      ''home'') }}'
  condition:
  - condition: state
    entity_id: input_boolean.heating_geolocation
    state: 'on'
  - condition: not
    conditions:
    - condition: zone
      entity_id: person.bauke
      zone: zone.home
    - condition: zone
      entity_id: person.anouk
      zone: zone.home
  action:
  - service: notify.notify
    data:
      title: Verwarming uitgeschakeld
      message: Je Tado is op 'afwezig' gezet omdat er niemand thuis is.
  - service: climate.set_preset_mode
    data:
      preset_mode: away
    target:
      area_id: woonkamer
  mode: single
- id: '1636147330332'
  alias: Schakel Tado in als er iemand thuis komt
  description: ''
  trigger:
  - platform: zone
    entity_id: person.anouk
    zone: zone.home
    event: enter
    id: sjdsab7yiu3h42j
  - platform: zone
    entity_id: person.bauke
    zone: zone.home
    event: enter
    id: dasd5u76ias8ud
  - platform: template
    value_template: '{{ is_state(''person.bauke'', ''home'') or is_state(''person.anouk'',
      ''home'') }}'
  condition:
  - condition: state
    entity_id: input_boolean.heating_geolocation
    state: 'on'
  - condition: state
    entity_id: climate.woonkamer
    state: away
    attribute: preset_mode
  action:
  - service: notify.notify
    data:
      title: Verwarming ingeschakeld
      message: Welkom thuis! Je Tado is ingeschakeld.
  - service: climate.set_preset_mode
    data:
      preset_mode: home
    target:
      area_id: woonkamer
  mode: single
- id: '1653435434932'
  alias: Sound the alarm iOS
  description: Motion based alarm
  trigger:
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: SOUND_ALARM
  condition: []
  action:
  - service: notify.persistent_notification
    data:
      title: Alarm gaat af
      message: test
  - service: notify.notify
    data:
      title: Alarm gaat af
      message: Test
  mode: single
- id: '1653685711883'
  alias: Turn on Movie Mode
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.movie_mode
    to: 'on'
  condition: []
  action:
  - service: light.turn_off
    target:
      area_id:
      - keuken
      - entree
    data:
      transition: 10
  - service: hue.hue_activate_scene
    data:
      scene_name: Film kijken
      group_name: Woonkamer
      dynamic: true
      transition: 10
  - service: switch.turn_off
    target:
      entity_id:
      - switch.hue_motion_sensor_1_motion
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
    data: {}
  mode: single
- id: '1653686032957'
  alias: Turn off Movie Mode
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.movie_mode
    to: 'off'
  condition: []
  action:
  - service: hue.hue_activate_scene
    data:
      scene_name: Helder
      group_name: Woonkamer
      dynamic: true
      transition: 10
  - service: switch.turn_on
    target:
      entity_id:
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
      - switch.hue_motion_sensor_1_motion
  mode: single
- id: '1654533597100'
  alias: Slaapkamer auto lights off
  description: Turn lights off after 30 minutes
  trigger:
  - device_id: 1c6a455d3533567404ec57126e82a5c8
    domain: hue
    platform: device
    type: short_release
    subtype: 1
    unique_id: c8c805fc-a934-4da1-903e-7756a7ef261b
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 30
      seconds: 0
      milliseconds: 0
  - type: turn_off
    device_id: a74e5afe63f2bb54544c6cb68f271511
    entity_id: light.hue_ambiance_spot_1
    domain: light
  - type: turn_off
    device_id: ae08ad1e58ab9a2e3092538b629abd07
    entity_id: light.hue_ambiance_spot_2
    domain: light
  - type: turn_off
    device_id: 290589317f10ecd65fe9cb6ea6f4a903
    entity_id: light.hue_ambiance_spot_3
    domain: light
  mode: single
- id: '1658504908669'
  alias: sleep_mode_on
  description: Turn off motion sensors on ground floor when Sleeping mode is on
  trigger:
  - platform: state
    entity_id: input_boolean.sleeping_mode
    to: 'on'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.hue_motion_sensor_1_motion
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
      - switch.hue_motion_sensor_1_motion_2
    data: {}
  - service: light.turn_off
    data: {}
    target:
      entity_id:
      - light.all_group
  mode: single
- id: '1658505514384'
  alias: sleep_mode_off
  description: Turn on motion sensors on ground floor when Sleeping mode is off
  trigger:
  - platform: state
    entity_id: input_boolean.sleeping_mode
    to: 'off'
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id:
      - switch.hue_motion_sensor_1_motion
      - switch.woonkamer_sensor_motion
      - switch.keuken_sensor_motion
  mode: single
- id: '1663687898960'
  alias: Livingroom Music Schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.livingroom_music_schedule
  condition: []
  action:
  - if:
    - condition: state
      state: 'on'
      entity_id: schedule.livingroom_music_schedule
    then:
    - service: media_player.media_play
      data: {}
      target:
        entity_id: media_player.woonkamer
    else:
    - service: media_player.media_stop
      data: {}
      target:
        entity_id: media_player.woonkamer
  mode: single
- id: '1664400231614'
  alias: Turn on Slaapkamer Motion sensor in the morning
  description: Turn on motion sensor Slaapkamer
  trigger:
  - platform: time
    at: 09:00:00
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.hue_motion_sensor_1_motion_2
  mode: single
- id: '1664454667785'
  alias: Notify when there is a lot of overproduction
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: ca489ceb3372a21d9b413f76f07d26c2
    entity_id: sensor.p1_meter_active_power
    domain: sensor
    below: -1500
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition:
  - condition: template
    value_template: '{{(as_timestamp(now()) - as_timestamp(state_attr("automation.notify_overproduction",
      "last_triggered") | default(0)) | int > 28800 )}}'
  action:
  - service: notify.notify
    data:
      title: Let the sun shine! ⚡️
      message: Je produceert nu veel stroom, tijd om een wasje te draaien?
  mode: single
- id: '1664540486301'
  alias: Turn on Schuurverwarming when enough PV overproduction
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: ca489ceb3372a21d9b413f76f07d26c2
    entity_id: sensor.p1_meter_active_power
    domain: sensor
    below: -750
    for:
      hours: 0
      minutes: 5
      seconds: 0
  condition:
  - condition: device
    type: is_off
    device_id: 524e63a9251c50afcac3f73c6e8866bb
    entity_id: light.elektrische_verwarming
    domain: light
  - condition: or
    conditions:
    - condition: zone
      entity_id: person.bauke
      zone: zone.home
    - condition: zone
      entity_id: person.anouk
      zone: zone.home
  - condition: not
    conditions:
    - condition: time
      after: 09:00:00
      before: '13:00:00'
  action:
  - service: notify.mobile_app_iphone_van_bauke
    data:
      title: Schuurverwarming ingeschakeld
      message: Genoeg overproductie ☀️
  - type: turn_on
    device_id: 524e63a9251c50afcac3f73c6e8866bb
    entity_id: light.elektrische_verwarming
    domain: light
  mode: single
- id: '1664540770914'
  alias: Turn off Schuurverwarming when not enough PV overproduction or at sunset
  description: ''
  trigger:
  - type: power
    platform: device
    device_id: ca489ceb3372a21d9b413f76f07d26c2
    entity_id: sensor.p1_meter_active_power
    domain: sensor
    for:
      hours: 0
      minutes: 2
      seconds: 0
    above: 0
  - platform: sun
    event: sunset
    offset: 0
  condition:
  - condition: state
    entity_id: light.elektrische_verwarming
    state: 'on'
  action:
  - service: notify.mobile_app_iphone_van_bauke
    data:
      title: Schuurverwarming uitgeschakeld
      message: Te weinig overproductie
  - type: turn_off
    device_id: 524e63a9251c50afcac3f73c6e8866bb
    entity_id: light.elektrische_verwarming
    domain: light
  mode: single
- id: '1664815772089'
  alias: sleep_mode_schedule
  description: ''
  trigger:
  - platform: state
    entity_id:
    - schedule.sleep_schedule
  condition: []
  action:
  - if:
    - condition: state
      entity_id: schedule.sleep_schedule
      state: 'on'
    then:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.sleeping_mode
    else:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.sleeping_mode
  mode: single
- id: '1666642536617'
  alias: security_garden_motion_detected
  description: Send a notification when motion is detected in the garden during the
    night
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.hue_outdoor_motion_sensor_1_motion
    to: 'on'
  condition:
  - condition: time
    after: '22:00:00'
    before: 08:00:00
  - condition: state
    entity_id: input_boolean.sleeping_mode
    state: 'on'
  action:
  - service: notify.notify
    data:
      message: Beweging gedetecteerd in de tuin
      title: Beveiliging
  mode: single
- id: '1667243249878'
  alias: sleep_mode_turn_off_mobile_activity
  description: Turn off Sleep Mode based on iPhone's activity
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.iphone_van_anouk_focus
    - binary_sensor.iphone_van_bauke_focus
    from: 'on'
    to: 'off'
  condition:
  - condition: time
    after: 07:30:00
    before: '10:30:00'
  - condition: state
    entity_id: input_boolean.sleeping_mode
    state: 'on'
  action:
  - service: input_boolean.turn_off
    data: {}
    target:
      entity_id: input_boolean.sleeping_mode
  mode: single
- id: '1667244491244'
  alias: tv_livingroom_pause_music
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.lg_tv
    to: 'on'
  condition:
  - condition: state
    entity_id: media_player.woonkamer
    state: playing
  action:
  - service: media_player.media_pause
    data: {}
    target:
      entity_id: media_player.woonkamer
  mode: single
- id: '1667575666527'
  alias: Movie Mode Toggle on/off
  description: ''
  trigger:
  - platform: state
    entity_id:
    - input_boolean.movie_mode
  condition: []
  action:
  - if:
    - condition: state
      entity_id: input_boolean.movie_mode
      state: 'on'
    then:
    - service: light.turn_off
      target:
        area_id:
        - keuken
        - entree
        - hal
      data:
        transition: 10
    - service: hue.hue_activate_scene
      data:
        scene_name: Film kijken
        group_name: Woonkamer
        dynamic: true
        transition: 10
    - service: switch.turn_off
      target:
        entity_id:
        - switch.hue_motion_sensor_1_motion
        - switch.woonkamer_sensor_motion
        - switch.keuken_sensor_motion
      data: {}
    else:
    - service: hue.hue_activate_scene
      data:
        scene_name: Helder
        group_name: Woonkamer
        dynamic: true
        transition: 20
    - service: switch.turn_on
      target:
        entity_id:
        - switch.woonkamer_sensor_motion
        - switch.keuken_sensor_motion
        - switch.hue_motion_sensor_1_motion
      data: {}
  mode: single
