# Home Assistant Configuration
homeassistant:
  name: Thuis
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/Amsterdam
  country: NL
  currency: EUR
  external_url: !secret hass_external_url
  internal_url: https://homeassistant.local:8123
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - /config

default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  login_attempts_threshold: 5
  ip_ban_enabled: true

frontend: !include themes.yaml
template: !include sidebar.yaml

lovelace: # Lovelace Resources
  mode: yaml
  resources:
    [
      { url: /hacsfiles/apexcharts-card/apexcharts-card.js,                         type: module },
      { url: /hacsfiles/bar-card/bar-card.js,                                       type: module },
      { url: /hacsfiles/button-card/button-card.js,                                 type: module },
      { url: /hacsfiles/custom-icons/custom-icons.js,                               type: module },
      { url: /hacsfiles/lovelace-layout-card/layout-card.js,                        type: module },
      { url: /hacsfiles/lovelace-more-info-card/more-info-card.js,                  type: module },
      { url: /hacsfiles/lovelace-mushroom/mushroom.js,                              type: module },
      { url: /hacsfiles/lovelace-slider-entity-row/slider-entity-row.js,            type: module },
      { url: /hacsfiles/swipe-card/swipe-card.js,                                   type: module },
      { url: /hacsfiles/lovelace-auto-entities/auto-entities.js,                    type: module },
    
      { url: '/local/marked.min.js?v=4.1.1',                                        type: module },
      { url: '/local/vanilla-tilt.min.js?v=1.7.2',                                  type: module },
      { url: '/local/browser_mod_icon.js?v=0.5',                                    type: module },
      { url: '/local/fonts.css?v=2.1',                                              type: css }
    ]

automation: !include automations.yaml
script: !include scripts.yaml

wake_on_lan: # enables `wake_on_lan` integration

input_select:
  who_moved_trash:
    name: Who moved the trash
    options:
      - default
      - Bauke
      - Anouk
    initial: default
    icon: mdi:account-star
    
input_boolean:
  heating_open_window_detection:
    name: Open raam detectie
    initial: true
  heating_geolocation:
    name: Auto-Assist Geolocatie
    initial: true
  movie_mode:
    name: Movie mode
    initial: false
    icon: mdi:filmstrip-box-multiple

switch:
  - platform: template
    switches:
     lg_tv:
       value_template: "{{ is_state('media_player.lg_tv', 'on') }}"
       turn_on:
         - service: wake_on_lan.send_magic_packet
           data:
               broadcast_address: !secret tv_ip
               mac: !secret tv_mac
       turn_off:
         service: media_player.turn_off
         entity_id: media_player.lg_tv

# HomeKit
homekit:
  filter:
    include_domains:
      - light
      - cover
      - switch
      - media_player
      - binary_sensor
     
sensor:
  - platform: time_date
    display_options:
      - time
      - date
  - platform: template
    sensors:
      living_room_tv_source:
        value_template: '{{ states.media_player.lg_tv.attributes["source"] }}'
        friendly_name: 'Living Room TV Source'
  - platform: template
    sensors:
      lights_on:
        value_template: '{{ states | selectattr("entity_id","in", ["light.globe", "light.plafondlamp","light.spot_bij_kast","light.spot_bij_raam","light.hue_globe_rechts","light.hue_globe_links"] )|selectattr("state","eq","on") | list | count }}'
        friendly_name: 'Lights on'
  - platform: template
    sensors:
      outside_temperature:
        value_template: '{{ states.weather.stille_steeg_west_12.attributes["temperature"] }}'
        friendly_name: 'Outside Temperature'
  - platform: rova
    zip_code: !secret home_zip_code
    house_number: !secret home_house_number
    name: Rova
    monitored_conditions:
      - bio
      - paper
      - plastic
  - platform: afvalwijzer
    provider: rova        # (required, default = mijnafvalwijzer) either choose mijnafvalwijzer, afvalstoffendienstkalender or rova
    postal_code: !secret home_zip_code              # (required, default = '')
    street_number:  !secret home_house_number                # (required, default = '')
    exclude_pickup_today: true        # (optional, default = false) to take or not to take Today into account in the next pickup.
    default_label: Geen              # (optional, default = Geen) label if no date found
    exclude_list: ''                 # (optional, default = '') comma separated list of wast types (case ignored). F.e. "papier, gft"
