background: var(--background-image)
custom_header:
  background: var(--primary-background-color);
  compact_mode: true
  elements_color: var(--primary-text-color);
  hide_help: true
  menu_dropdown: true
  tab_indicator_color: var(--primary-text-color);
title: Lange Heul
views:
  - badges: []
    cards:
      - cards:
          - content: >-
              Paper and cardboard will be collected in
              {{states('sensor.gad_papier_days')}} day(s)
            style: |
              ha-card {
                background-color: unset;
                box-shadow: unset;  
              }
            type: markdown
        title: Notifications
        type: vertical-stack
      - cards:
          - cards:
              - icon: 'mdi:lightbulb-multiple'
                show_icon: true
                show_name: false
                style: |
                  ha-card {
                    margin: 10px;
                    box-shadow: 
                      {% if is_state('sun.sun', 'above_horizon') %}
                        -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                      {% elif is_state('sun.sun', 'below_horizon') %}
                        -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
                      {% endif %}                 
                  }
                styles:
                  card:
                    - width: 80px
                    - height: 80px
                    - border-radius: 15px
                    - background-color: var(--primary-background-color)
                  icon:
                    - color: var(--primary-text-color)
                tap_action:
                  action: navigate
                  haptic: light
                  navigation_path: /lovelace/lights
                type: 'custom:button-card'
              - cards:
                  - content: |
                      # Lights
                    style: |
                      ha-card {
                        height: 20px;                  
                        --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
                        box-shadow: 2px 2px rgba(0,0,0,0.0);
                      }
                      h1 {
                        font-size: 20px;
                        font-weight: bold;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
                    type: markdown
                  - content: >
                      # There are  {% if is_state('sensor.lights_on', '0') %}
                      currently no  {% else %}  {{states('sensor.lights_on')}} 
                      {% endif %} lights on
                    style: |
                      ha-card {
                      --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                         }
                      h1 {
                        font-size: 15px;
                        font-weight: thin;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
                    type: markdown
                type: vertical-stack
            type: horizontal-stack
          - cards:
              - icon: 'mdi:thermometer'
                show_icon: true
                show_name: false
                style: |
                  ha-card {
                    margin: 10px;
                    box-shadow: 
                      {% if is_state('sun.sun', 'above_horizon') %}
                        -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                      {% elif is_state('sun.sun', 'below_horizon') %}
                        -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
                      {% endif %}                 
                  }
                styles:
                  card:
                    - width: 80px
                    - height: 80px
                    - border-radius: 15px
                    - background-color: var(--primary-background-color)
                  icon:
                    - color: var(--primary-text-color)
                tap_action:
                  action: navigate
                  haptic: light
                  navigation_path: /lovelace/temperature
                type: 'custom:button-card'
              - cards:
                  - content: |
                      # Temperature
                    style: |
                      ha-card {
                        height: 20px;                  
                        --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
                        box-shadow: 2px 2px rgba(0,0,0,0.0);
                      }
                      h1 {
                        font-size: 20px;
                        font-weight: bold;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
                    type: markdown
                  - content: >
                      # The temperature is {{
                      states('sensor.woonkamer_sensor_temperature') }} {{
                      state_attr('sensor.woonkamer_sensor_temperature',
                      'unit_of_measurement')}}
                    style: |
                      ha-card {
                      --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
                      box-shadow: 2px 2px rgba(0,0,0,0.0);
                         }
                      h1 {
                        font-size: 15px;
                        font-weight: thin;
                        font-family: Helvetica;
                        letter-spacing: '-0.01em';
                      }
                    type: markdown
                type: vertical-stack
            type: horizontal-stack
        type: vertical-stack
    icon: 'mdi:home'
    path: default_view
    title: Home
  - badges: []
    cards: []
    icon: 'mdi:lightbulb-multiple'
    path: lights
    title: Lights
  - badges: []
    cards:
      - cards:
          - entity: sensor.woonkamer_sensor_temperature
            graph: line
            style: |
              :host {
                border-radius: 15px;
                margin: 10px !important;
                overflow: hidden;
                box-shadow: 
                  {% if is_state('sun.sun', 'above_horizon') %}
                    -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                  {% else %}
                    -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
                  {% endif %}   
              }
              ha-card {
                  background-color: var(--primary-background-color);
              }
            type: sensor
          - entity: sensor.hal_sensor_temperature
            graph: line
            style: |
              :host {
                border-radius: 15px;
                margin: 10px !important;
                overflow: hidden;
                box-shadow: 
                  {% if is_state('sun.sun', 'above_horizon') %}
                    -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                  {% else %}
                    -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
                  {% endif %}   
              }
              ha-card {
                  background-color: var(--primary-background-color);
              }
            type: sensor
        type: horizontal-stack
    icon: 'mdi:thermometer'
    path: temperature
    title: Temperature
  - badges:
      - entity: person.bauke
      - entity: person.anouk
        entity_picture: >-
          https://lh3.googleusercontent.com/-WEkakiV1t6Q/AAAAAAAAAAI/AAAAAAAAAAA/AMZuucnqDOqJGEXbMqrkBU1LDjXHrP3-VA.CMID/s83-c/photo.jpg
    cards:
      - cards:
          - icon: 'mdi:lightbulb-multiple'
            show_icon: true
            show_name: false
            style: |
              ha-card {
                margin: 10px;
                box-shadow: 
                  {% if is_state('sun.sun', 'above_horizon') %}
                    -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                  {% elif is_state('sun.sun', 'below_horizon') %}
                    -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
                  {% endif %}                 
              }
            styles:
              card:
                - width: 80px
                - height: 80px
                - border-radius: 15px
                - background-color: var(--primary-background-color)
              icon:
                - color: var(--primary-text-color)
            tap_action:
              action: navigate
              haptic: light
              navigation_path: /lovelace/lights
            type: 'custom:button-card'
          - cards:
              - content: |
                  # Lights
                style: |
                  ha-card {
                    height: 20px;                  
                    --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
                    box-shadow: 2px 2px rgba(0,0,0,0.0);
                  }
                  h1 {
                    font-size: 20px;
                    font-weight: bold;
                    font-family: Helvetica;
                    letter-spacing: '-0.01em';
                  }
                type: markdown
              - content: >
                  # There are  {% if is_state('sensor.lights_on', '0') %}
                  currently no  {% else %}  {{states('sensor.lights_on')}}  {%
                  endif %} lights on
                style: |
                  ha-card {
                  --paper-card-background-color: 'rgba(11, 11, 11, 0.00)';
                  box-shadow: 2px 2px rgba(0,0,0,0.0);
                     }
                  h1 {
                    font-size: 15px;
                    font-weight: thin;
                    font-family: Helvetica;
                    letter-spacing: '-0.01em';
                  }
                type: markdown
            type: vertical-stack
        type: horizontal-stack
      - cards:
          - entities:
              - entity: group.living_room_lights
              - entity: group.hall_lights
              - entity: group.bedroom_lights
            show_header_toggle: false
            style: |
              ha-card {
                background-color: var(--primary-background-color);
                border-radius: 15px;
                margin: 10px;
                box-shadow: 
                  {% if is_state('sun.sun', 'above_horizon') %}
                    -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                  {% else %}
                    -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
                  {% endif %}   
              }
            title: Lights
            type: entities
          - entities:
              - entity: vacuum.roborock_s6
            show_header_toggle: false
            style: |
              ha-card {
                background-color: var(--primary-background-color);
                border-radius: 15px;
                margin: 10px;
                box-shadow: 
                  {% if is_state('sun.sun', 'above_horizon') %}
                    -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                  {% else %}
                    -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
                  {% endif %}   
              }
            title: Vacuum
            type: entities
          - entities:
              - entity: light.espressomachine
            style: |
              ha-card {
                background-color: var(--primary-background-color);
                border-radius: 15px;
                margin: 10px;
                box-shadow: 
                  {% if is_state('sun.sun', 'above_horizon') %}
                    -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
                  {% else %}
                    -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
                  {% endif %}   
              }
            title: Kitchen
            type: entities
        show_header_toggle: false
        type: vertical-stack
      - entity: weather.lange_heul
        type: weather-forecast
      - entities:
          - entity: sensor.netherlands_coronavirus_confirmed
          - entity: sensor.netherlands_coronavirus_deaths
          - entity: sensor.netherlands_coronavirus_recovered
        style: |
          ha-card {
            background-color: var(--primary-background-color);
            border-radius: 15px;
            margin: 10px;
            box-shadow: 
              {% if is_state('sun.sun', 'above_horizon') %}
                -8px -8px 8px 0 rgba(255,255,255,.5),8px 8px 8px 0 rgba(0,0,0,.03);
              {% else %}
                -8px -8px 8px 0 rgba(50, 50, 50,.5),8px 8px 8px 0 rgba(0,0,0,.15);
              {% endif %}   
          }
        title: Corona in The Netherlands
        type: glance
      - cards:
          - entity: sensor.woonkamer_sensor_temperature
            graph: line
            type: sensor
          - entity: sensor.hal_sensor_temperature
            graph: line
            type: sensor
        type: horizontal-stack
      - entities:
          - entity: sensor.gad_papier_days_stringified
            icon: 'mdi:package-variant'
            name: Papier en karton
        show_header_toggle: false
        title: GAD Afvalbeheer
        type: entities
      - entity: media_player.playstation_4
        type: media-control
      - entities:
          - entity: person.bauke
          - entity: person.anouk
        hours_to_show: 24
        refresh_interval: 0
        title: Persons
        type: history-graph
      - entity: media_player.lg_tv
        type: media-control
      - entity: vacuum.roborock
        image: default
        type: 'custom:vacuum-card'
    icon: 'mdi:dev-to'
    path: dev
    title: DEV
    visible:
      - user: 6f0d1b6b95e841f9a7e4e1e082657153
