homeassistant: true
mqtt:
  server: mqtt://192.168.178.100/
  user: mqtt_user
  password: b1122pb1122p
serial:
  port: /dev/ttyUSB0
frontend:
  port: 8099
devices:
  '0x680ae2fffe80376e':
    friendly_name: Ikea on/off button
    legacy: false
    simulated_brightness: {}
