adaptive_lighting:
  - name: Badkamer
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.badkamer_group
  - name: Keuken
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.keuken_group
  - name: Woonkamer
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.woonkamer_group
  - name: Entree
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.entree_group
  - name: Slaapkamer
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.slaapkamer_group
  - name: Werkkamer
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.werkkamer_bauke_group
  - name: Studio
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.werkkamer_anouk_group
  - name: Logeerkamer
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.logeerkamer_group
  - name: Hal
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.hal_group
  - name: Overloop
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.overloop_group
  - name: Toilet
    min_brightness: 15
    initial_transition: 0.25
    lights:
      - light.toilet_group

automation:
  - id: 35kj5sdhas93249325hdsf093
    alias: "Adaptive lighting: toggle 'sleep mode'"
    trigger:
      - platform: state
        entity_id: input_boolean.sleep_mode
      - platform: homeassistant
        event: start  # in case the states aren't properly restored
    variables:
      sleep_mode: "{{ states('input_boolean.sleep_mode') }}"
    action:
      service: "switch.turn_{{ sleep_mode }}"
      entity_id:
        - switch.adaptive_lighting_sleep_mode_badkamer
        - switch.adaptive_lighting_sleep_mode_keuken
        - switch.adaptive_lighting_sleep_mode_woonkamer
        - switch.adaptive_lighting_sleep_mode_entree
        - switch.adaptive_lighting_sleep_mode_slaapkamer
        - switch.adaptive_lighting_sleep_mode_werkkamer
        - switch.adaptive_lighting_sleep_mode_studio
        - switch.adaptive_lighting_sleep_mode_logeerkamer
        - switch.adaptive_lighting_sleep_mode_hal
        - switch.adaptive_lighting_sleep_mode_overloop
        - switch.adaptive_lighting_sleep_mode_toilet
