schedule:
  espressomachine_schedule:
    name: "Espressomachine schedule"
    monday:
      - from: "09:00:00"
        to: "20:00:00"
    tuesday:
      - from: "09:00:00"
        to: "20:00:00"
    wednesday:
      - from: "09:00:00"
        to: "20:00:00"
    thursday:
      - from: "09:00:00"
        to: "20:00:00"
    friday:
      - from: "09:00:00"
        to: "20:00:00"
    saturday:
      - from: "10:00:00"
        to: "20:00:00"
    sunday:
      - from: "10:00:00"
        to: "20:00:00"
automation:
  - alias: Espressomachine schedule
    description: 'Turn on espresso machine based on schedule and current solar production'
    id: '3846283537458'
    trigger:
      - platform: numeric_state
        entity_id: sensor.power_production_now
        above: 1400
        for:
          hours: 0
          minutes: 1
          seconds: 0
      - platform: state
        entity_id: schedule.espressomachine_schedule
    condition:
      - condition: state
        entity_id: schedule.espressomachine_schedule
        state: 'on'
      - condition: device
        type: is_off
        device_id: 29d22d3df71910ad86405bb7d5154123
        entity_id: light.espressomachine
        domain: light
      - condition: or
        conditions:
        - condition: zone
          entity_id: person.bauke
          zone: zone.home
        - condition: zone
          entity_id: person.anouk
          zone: zone.home
    action:
      - service: notify.notify
        data:
          message: Er is genoeg overproductie ☀️
          title: Espresso Machine ingeschakeld
      - type: turn_on
        device_id: 29d22d3df71910ad86405bb7d5154123
        entity_id: light.espressomachine
        domain: light
  - alias: Turn on Espresso Machine at 12:00 when not enough PV production
    id: '1664802828599'
    description: ''
    trigger:
    - platform: time
      at: '12:00:00'
    condition:
    - condition: device
      type: is_off
      device_id: 29d22d3df71910ad86405bb7d5154123
      entity_id: light.espressomachine
      domain: light
    - condition: state
      entity_id: schedule.espressomachine_schedule
      state: 'on'
    - condition: or
      conditions:
      - condition: zone
        entity_id: person.bauke
        zone: zone.home
      - condition: zone
        entity_id: person.anouk
        zone: zone.home
    action:
    - service: notify.notify
      data:
        message: "Er is te weinig zonne energie \U0001F976"
        title: Espresso Machine ingeschakeld
    - type: turn_on
      device_id: 29d22d3df71910ad86405bb7d5154123
      entity_id: light.espressomachine
      domain: light
    mode: single
