input_boolean:
  guest_mode:
    name: Guest mode
    initial: false
    icon: mdi:bed

  guest_home:
    name: Guest home state
    initial: false
    icon: mdi:home
    
person:
  - name: Robin
    id: guest1
    device_trackers:
      - device_tracker.robin
  - name: Vivianne
    id: guest2
    device_trackers:
      - device_tracker.vivianne
      
notify:
  - platform: group
    name: "Guests"
    services:
      - service: robin
      - service: vivianne

automation:
  - alias: guest_leave
    id: '3840027582367'
    description: 'When guests leave the home'
    trigger:
      - platform: state
        entity_id: input_boolean.guest_home
        to: 'off'
    action:
      - service: script.leave_home
    mode: restart
  - alias: guest_arrive
    id: '8340728312935'
    description: 'When guests arrive home'
    trigger:
      - platform: state
        entity_id: input_boolean.guest_home
        to: 'on'
    action:
      - service: script.arrive_home
    mode: single
  - alias: guest_leave_geolocation
    id: '57382849534053'
    description: 'When guests leave the home based on GPS'
    trigger:
      - platform: zone
        entity_id: person.guest1
        zone: zone.home
        event: leave
        id: dsjfufg8eug8fi
      - platform: zone
        entity_id: person.guest2
        zone: zone.home
        event: leave
        id: hfjdk9dfhgu8sw
    condition:
      - condition: not
        conditions:
          - condition: zone
            entity_id: person.bauke
            zone: zone.home
          - condition: zone
            entity_id: person.anouk
            zone: zone.home
    action:
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.guest_home
    mode: single
  - alias: guest_arrive_geolocation
    id: '473843849572394'
    description: 'When guests arrive home based on GPS'
    trigger:
      - platform: zone
        entity_id: person.guest1
        zone: zone.home
        event: enter
        id: fhdjujf7eph8x9
      - platform: zone
        entity_id: person.guest2
        zone: zone.home
        event: enter
        id: kvo0rvardu37dc
    action:
      - service: input_boolean.turn_on
        target:
          entity_id: input_boolean.guest_home
    mode: single
