homeassistant:
  customize:
    person.bauke:
      entity_picture: !secret profile_photo_bauke
    device_tracker.iphone_van_bauke:
      entity_picture: /local/device_tracker.svg
    person.anouk:
      entity_picture: !secret profile_photo_anouk
    device_tracker.iphone_van_anouk:
      entity_picture: /local/device_tracker.svg

person:
  - name: Bauke
    id: bauke
    device_trackers:
      - device_tracker.iphone_van_bauke
  - name: Anouk
    id: anouk
    device_trackers:
      - device_tracker.iphone_van_anouk

notify:
  - platform: group
    name: Family
    services:
      - service: iphone_van_bauke
      - service: iphone_van_anouk

automation:
  - id: '1673735955790'
    alias: When arriving home
    description: Main automation for when a family member arrives home
    trigger:
      - platform: zone
        entity_id: 
          - person.bauke
          - person.anouk
        zone: zone.home
        event: enter
    condition: []
    action:
      - service: notify.family
        data:
          message: |
            {% if trigger.entity_id %}
              Welkom thuis {{ state_attr(trigger.entity_id, 'friendly_name') }}!
            {% else %}
              Welkom thuis!
            {% endif %}
      - service: script.turn_on
        target:
          entity_id: script.turn_on_outdoor_lights_for_5_minutes
      - service: script.turn_on
        target:
          entity_id: script.turn_on_motion_sensors_for_pet_accessible_rooms
      - if:
        - condition: state
          entity_id: input_boolean.heating_geolocation
          state: 'on'
        - condition: state
          entity_id: climate.woonkamer
          state: away
          attribute: preset_mode
        then:
          - service: climate.set_preset_mode
            data:
              preset_mode: home
            target:
              area_id: woonkamer
    mode: single
  - id: '1673736147327'
    alias: When leaving home
    description: Main automation for when last family member leaves the home
    trigger:
      - platform: zone
        entity_id: 
          - person.bauke
          - person.anouk
        zone: zone.home
        event: leave
    condition: []
    action:
      - if:
        - condition: not
          conditions:
            - condition: zone
              entity_id: 
                - person.bauke
              zone: zone.home
            - condition: zone
              entity_id: 
                - person.anouk
              zone: zone.home
        then:
          - service: notify.family
            data:
              title: |
                {% if trigger.entity_id %}
                  Tot ziens {{ state_attr(trigger.entity_id, 'friendly_name') }}!
                {% else %}
                  Tot ziens!
                {% endif %}
              message: De verwarming en alle apparaten worden uitgeschakeld
          - service: script.turn_on
            target:
              entity_id: script.turn_off_motion_sensors_for_pet_accessible_rooms
          - service: script.turn_on
            target:
              entity_id: script.turn_off_all_lights_and_devices
          - condition: state
            entity_id: input_boolean.heating_geolocation
            state: 'on'
          - service: climate.set_preset_mode
            data:
              preset_mode: away
            target:
              area_id: woonkamer
        else:
          - service: notify.family
            data:
              message: |
                {% if trigger.entity_id %}
                  Tot ziens {{ state_attr(trigger.entity_id, 'friendly_name') }}!
                {% else %}
                  Tot ziens!
                {% endif %}
    mode: single

# mqtt:
#   sensor:
#     - name: bauke_last_changed
#       state_topic: homeassistant/persistence/bauke
#       value_template: >
#         {{ value | replace(' ', 'T') }}

#     - name: anouk_last_changed
#       state_topic: homeassistant/persistence/anouk
#       value_template: >
#         {{ value | replace(' ', 'T') }}

# automation:
#   - alias: person_home
#     id: '8423590985012'
#     mode: parallel
#     trigger:
#       platform: state
#       entity_id:
#         - person.bauke
#         - person.anouk
#       from:
#         - home
#         - not_home
#       to:
#         - home
#         - not_home
#     action:
#       service: mqtt.publish
#       data:
#         topic_template: >
#           homeassistant/persistence/{{ trigger.to_state.name | lower }}
#         payload_template: >
#           {{ now() }}
#         retain: true

# Sleeping bayesian sensor
binary_sensor:
  - name: 'Bauke sleeping'
    platform: bayesian
    probability_threshold: 0.85
    prior: 0.5
    observations:
      - entity_id: 'device_tracker.iphone_van_bauke'
        prob_given_true: 0.99
        prob_given_false: 0.5
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sun.sun'
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'below_horizon'
      - entity_id: 'sensor.last_motion'
        prob_given_true: 0.9
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'Slaapkamer sensor Motion'
      - entity_id: 'sensor.iphone_van_bauke_battery_state'
        prob_given_true: 0.95
        prob_given_false: 0.5
        platform: 'state'
        to_state: 'Charging'
  - name: 'Anouk sleeping'
    platform: bayesian
    prior: 0.5
    probability_threshold: 0.85
    observations:
      - entity_id: 'device_tracker.iphone_van_anouk'
        prob_given_true: 0.99
        prob_given_false: 0.5
        platform: 'state'
        to_state: 'home'
      - entity_id: 'sun.sun'
        prob_given_true: 0.9
        prob_given_false: 0.2
        platform: 'state'
        to_state: 'below_horizon'
      - entity_id: 'sensor.last_motion'
        prob_given_true: 0.9
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'Slaapkamer sensor Motion'
      - entity_id: 'sensor.iphone_van_anouk_battery_state'
        prob_given_true: 0.95
        prob_given_false: 0.5
        platform: 'state'
        to_state: 'Charging'

template:
  - sensor:
      - name: "Last Motion"
        icon: mdi:motion-sensor
        state: >
          {% set sensors = [
            states.binary_sensor.badkamer_sensor_motion,
            states.binary_sensor.hue_motion_sensor_1_motion,
            states.binary_sensor.hal_sensor_motion,
            states.binary_sensor.keuken_sensor_motion,
            states.binary_sensor.overloop_sensor_motion,
            states.binary_sensor.hue_motion_sensor_1_motion_2,
            states.binary_sensor.toilet_sensor_motion,
            states.binary_sensor.hue_outdoor_motion_sensor_1_motion,
            states.binary_sensor.hue_outdoor_motion_sensor_2_motion,
            states.binary_sensor.werkkamer_anouk_sensor_motion,
            states.binary_sensor.hue_motion_sensor_1_motion_3,
            states.binary_sensor.woonkamer_sensor_motion
          ] %}
          {% set time = sensors | map(attribute='last_changed') | max %}
          {% set sensor = (sensors | selectattr('last_changed', 'eq', time) | list)[0] %}
          {{sensor.name}}
