homeassistant:
  customize:
    switch.galaxy_tab_a8_screensaver:
      friendly_name: Screensaver
      icon: mdi:power-sleep
    number.galaxy_tab_a8_screen_brightness:
      friendly_name: Display
      icon: mdi:tablet
    switch.galaxy_tab_a8_screen:
      friendly_name: Display
      icon: mdi:tablet
    binary_sensor.galaxy_tab_a8_plugged_in:
      friendly_name: Stroomvoorziening
      icon: mdi:power-plug
    sensor.galaxy_tab_a8_last_app_start:
      friendly_name: Laatste herstart
      icon: mdi:update
    sensor.galaxy_tab_a8_battery:
      friendly_name: Batterij

template:
  - sensor:
      - unique_id: fullykiosk_storage
        state: >
          {% set FreeSpace = states('sensor.galaxy_tab_a8_internal_storage_free_space') | float(default=0) %}
          {% set TotalSpace = states('sensor.galaxy_tab_a8_internal_storage_total_space') | float(default=0) %}
          {% if not (FreeSpace == 0.0 or TotalSpace == 0.0) %}
            {{ 100 - (FreeSpace / TotalSpace * 100) | int(default=0) }}
          {% endif %}
        attributes:
          friendly_name: Opslag
          icon: mdi:sd
          unit_of_measurement: '%'

      - unique_id: fullykiosk_memory
        state: >
          {% set FreeMemory = states('sensor.galaxy_tab_a8_free_memory') | float(default=0) %}
          {% set TotalMemory = states('sensor.galaxy_tab_a8_total_memory') | float(default=0) %}
          {% if not (FreeMemory == 0.0 or TotalMemory == 0.0) %}
            {{ 100 - (FreeMemory / TotalMemory * 100) | int(default=0) }}
          {% endif %}
        attributes:
          friendly_name: Geheugen
          icon: mdi:memory
          unit_of_measurement: '%'

automation:
  - alias: homeassistant_start
    id: '7426848686945'
    trigger:
      platform: homeassistant
      event: start
    action:
      - service: button.press
        target:
          entity_id: button.galaxy_tab_a8_load_start_url
      - delay:
          minutes: 1
      - if:
          condition: state
          entity_id: light.hall
          state: 'off'
        then:
          service: switch.turn_on
          target:
            entity_id: switch.galaxy_tab_a8_screensaver

  - alias: ios_notify_tablet_unplugged
    id: '3972668118831'
    trigger:
      platform: numeric_state
      entity_id: sensor.galaxy_tab_a8_battery
      below: 50
    action:
      service: notify.all_devices
      data:
        title: Laadt de tablet op...
        message: >
          Batterij {{ states(trigger.entity_id) }}%
