input_boolean:
  waste_moved:
    name: Waste has been moved
    initial: false
    icon: mdi:delete-empty
  waste_reminder:
    name: Waste reminder
    initial: true
    icon: mdi:bell-ring

automation:
  - alias: waste_moved_reset
    id: fb01f50f6e484d7fb623365e9a0b5f52
    trigger:
      platform: state
      entity_id: input_boolean.waste_moved
      to: 'on'
      for:
        hours: 16
    action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.waste_moved
    - service: input_boolean.turn_on
      entity_id: input_boolean.waste_reminder
  - alias: mark_waste_moved
    id: f276d37dd7b4490d9e5212c91fdeeba0
    trigger:
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MARK_WASTE_MOVED
      id: waste_moved_by_bauke
      context:
        user_id:
        - f976a4bc7f22438e93c9a9cd0b47c627
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MARK_WASTE_MOVED
      id: waste_moved_by_anouk
      context:
        user_id:
        - 630c9bfb3f084bf1b7133da9a16ff5ec
    - platform: event
      event_type: ios.notification_action_fired
      event_data:
        actionName: MARK_WASTE_MOVED
      context: {}
    action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.waste_moved
    - choose:
      - conditions:
        - condition: trigger
          id: waste_moved_by_bauke
        sequence:
        - service: input_select.select_option
          target:
            entity_id: input_select.who_moved_trash
          data:
            option: Bauke
      - conditions:
        - condition: trigger
          id: waste_moved_by_anouk
        sequence:
        - service: input_select.select_option
          target:
            entity_id: input_select.who_moved_trash
          data:
            option: Anouk
      default:
      - service: input_select.select_option
        target:
          entity_id: input_select.who_moved_trash
        data:
          option: default
    - service: notify.notify
      data:
        title: '{{ states.input_select.who_moved_trash.state }} heeft de {% if is_state(''sensor.afvalwijzer_tomorrow'',
          ''Geen'') %}vuilnis{% else %}{{states.sensor.afvalwijzer_tomorrow.state}}{%
          endif %} container buiten gezet'
        message: Chill, dan hoef jij het niet meer te doen!
    - service: input_select.select_option
      target:
        entity_id: input_select.who_moved_trash
      data:
        option: default
  - alias: waste_alert
    id: b95aa77fdde0437e9f7a65d0d7bfe860
    trigger:
    - platform: time_pattern
      hours: /1
    condition:
    - condition: and
      conditions:
      - condition: state
        entity_id: input_boolean.waste_moved
        state: 'off'
      - condition: state
        entity_id: input_boolean.waste_reminder
        state: 'on'
      - condition: time
        after: '18:00:00'
        before: '23:00:00'
      - condition: template
        value_template: '{{ states(''sensor.afvalwijzer_tomorrow'') != ''Geen'' }}'
    action:
    - service: notify.notify
      data:
        title: Afvalinzameling
        message: >-
          Morgen wordt het {% if is_state('sensor.afvalwijzer_tomorrow', 'Geen') %}afval{% else %}{{states.sensor.afvalwijzer_tomorrow.state}}{% endif %} opgehaald, zet jij de container buiten?
        data:
          actions:
          - action: MARK_WASTE_MOVED
            title: Voltooien
            icon: sfsymbols:checkmark.circle
          - action: DISMISS
            title: Herinner mij later
            icon: sfsymbols:timer
