sensor:
  - platform: buienalarm
    timeframe: 60
    name: buienalarm
    monitored_conditions:
      - temperature
      - precipitation
      - precipitation_forecast_average
      - precipitation_forecast_total
      - next_rain_forecast
template:
  - sensor:
    - name: "Buienalarm Next rain forecast"
      unit_of_measurement: "min"
      state: >
        {% if as_timestamp(states('sensor.buienalarm_next_rain_forecast')) %}
          {{ ( ( as_timestamp(states('sensor.buienalarm_next_rain_forecast')) - as_timestamp(now()) ) / 60 ) | round }}
        {% else %}
          {{ states('nonexistent') }}
        {% endif %}
